### ISSUE TITLE
scikit learn API 'cross_val_score'

### ISSUE THREAD

**Issue by yiyuchen-lab** [braindecode/braindecode#172]
Does braindecode support training using 'cross_val_score' from scikit-learn?

**Comment by gemeinl** [comment]
Hi @yiyuchen-lab,
I just gave it a try and it does not seem to work out of the box, due to several reasons:
1. As our datasets are pytorch Datasets they return both x and y (and ind). For this, skorch has a workaround called ```SliceDataset``` with ```idx``` set to 0 to get x and 1 to get y (see https://skorch.readthedocs.io/en/stable/helper.html#skorch.helper.SliceDataset). However, one will lose the compute window indeces when doing this, which limits oneself to perform trialwise decoding only.
2. For cross_val_score and cross_val_predict scikit-learn clones the estimator which resulted in an error for me (```TypeError: __init__() got an unexpected keyword argument 'on_train'```). For some reason scikit-learn expects our ```PostEpochTrainScoring``` to accept this argument (which it does not, but it is used and set to true to initialize super()). To further investigate possible limitations, I added ```on_train``` and ```use_caching``` to the ```__init__()``` of ```PostEpochTrainScoring```, but never use the values.
3. Our wrapping ```EEGClassifier``` of skorch.classifier apparently violates some scikit-learn estimator rules (```RuntimeError: Cannot clone object <class 'braindecode.classifier.EEGClassifier'>[initialized]``` ...., ```as the constructor either does not set or modifies parameter callbacks```), so right now it cannot be used.

If you want to perform trialwise decoding and still use braindecode datasets, you could try as follows. First create a skorch NeuralNetClassifier, where model, i.e. ShallowFBCSPNet or Deep4, accepts 4d input data as (bach_size x eeg_channels x time_points x 1)
```
import torch
from skorch.classifier import NeuralNetClassifier
clf = NeuralNetClassifier(
    model,
    max_epochs=1,
    criterion=torch.nn.NLLLoss,
    train_split=None
)
```
Second, call ```cross_val_score``` on slices of braindecode datasets:
```
from sklearn.model_selection import cross_val_score
from skorch.helper import SliceDataset
cross_val_score(
    clf, 
    X=SliceDataset(train_set, idx=0), 
    y=SliceDataset(train_set, idx=1), 
    cv=2,
    scoring="accuracy",
)
```
Please note that this is only a description of steps to get the code running, however, I did not verify any computations or results.

**Comment by yiyuchen-lab** [comment]
thank you very much!
