### ISSUE TITLE
Dataset improvements, including Incosistency and inefficiency of description

### ISSUE THREAD

**Issue by gemeinl** [braindecode/braindecode#189]
Each `BaseDataset` has a pandas Series holding valuable information.
When creating a `BaseConcatDataset` description is currently copied into a DataFrame.
Users might want to change the description from the outside, for example adding the number of compute windows after windowing, which will result in inconsistent descriptions.

Suggested imrpovement:
`BaseConcatDataset` should not copy descriptions of `BaseDataset`.
It should instead provide a getter which concatenates all descriptions when called.
In addition, it should provide a setter which adds an entry to the description of `BaseDataset`.

**Comment by hubertjb** [comment]
I like the idea. Only reason I see this could be problematic is if the concatenation of pd.Series is slow. I guess this is not likely to happen though as datasets usually don't have more than a few thousands of `description` series?

**Comment by gemeinl** [comment]
`description` is used at rare occasions in our code. One place would be the splitting of datasets which is typically not required to be fast. It is more for convenience and called specifically by the user. If he intends to call it many times, he could create a copy.

I just realized that there is another copy of the `description` in the `WindowsDataset`.
Also, to me it is not ideal that the windowing functions do not take care of the `BaseDataset` / raw signals.
I feel like the `WindowsDataset` should replace the `BaseDataset` in the `BaseConcatDataset` or the windowing functions could give an option to delete the raws afterwards. Any thoughts on this?

**Comment by hubertjb** [comment]
So to summarize, we have copies of `description` in `BaseDataset`, `WindowsDataset` and `BaseConcatDataset`. You're suggesting we don't actually copy `description` when creating `WindowsDatasets` or `BaseConcatDatasets`, but instead to provide getters to dynamically create `description` based on the underlying `BaseDataset`. Is that right? If so, I agree that `BaseConcatDataset` should probably collect `descriptions` dynamically. However, just to be clear, I believe`WindowsDataset` would still need its own copy since you can have a `BaseConcatDataset` that only encapsulates `WindowsDatasets`.

As for the windowers taking care of the `BaseDataset`, I agree that we could have something like an `inplace` argument that controls whether we overwrite the input `BaseConcatDataset` by the output of the windowers.

**Comment by robintibor** [comment]
* multi-target
   * description part uses target column, a bit limiting
   * maybe keep target as a separated variable (like numpy array that can be returned)
      * might be possible to keep in dataframe column, but do we want that? 
* ECoG sampled at 500 Hz, target sampled at 10 hz... what to do?
   * one can create events for targets, can this be done better? 
   * tutorial for this? what is best practice for this?
   * might want to change sampling rate (even resample targets?)
   * large window, how to synchronize with target?
   * return/access multiple targets within window
 * Structure seems a bit complicated of the datasets? Can it be simplified?
 * We also get a bit inconsistent stuff from MOABB
   * Should we create issue on MOABB? 
 * Description (also see above)
   * We may need getters/setters, potentially as properties
* Epoch/Trial Rejection
  * first one window per trial, reject
  * "rewindow" into more windows
  * reject at each step? would be great?

MNE channels all have same sampling rate (would need to upsample targets)
* so for different sampling rate would need two MNE raw files

**Comment by gemeinl** [comment]
@sylvchev Is working on more consistent naming of sessions/runs on the MOABB side https://github.com/NeuroTechX/moabb/issues/208.

**Comment by robintibor** [comment]
Amazing stuff, great you mentioned to them!
