### ISSUE TITLE
Documention website is not available

### ISSUE THREAD

**Issue by jcuan** [braindecode/braindecode#217]
https://braindecode.org/

404 There isn't a GitHub Pages site here.

**Comment by sliwy** [comment]
Thanks for reporting that! 
Actually our GitHub Pages site is accessible but under another address. Until we fix this problem you can access the current master documentation here [https://braindecode.github.io/]()

@robintibor I think that it may be a problem with forwarding between web addresses because GitHub Pages site is working, maybe try to check in the admin panel of the braindecode.org domain?

**Comment by robintibor** [comment]
Thanks @sliwy @jcuan should be fixed now, had to readd CNAME file in https://github.com/braindecode/braindecode.github.io/commit/52ddce9ff30ed723cdfe00b40bac0d70773d9cf2. https://braindecode.org working from my side again. Still waiting for github actions to see if fix through https://github.com/braindecode/braindecode/commit/fccc4d76b2d52f2242d94debf98717de237a5a06 also works (Github Actions some issues atm as per https://www.githubstatus.com/).

**Comment by robintibor** [comment]
Everything seems working fine now, thanks for your notice again, let us know if problems reappear.
