### ISSUE TITLE
Add Specific Data Augmentations

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#240]
Could be nice to add standard augmentations like MixUp/Cutout into Braindecode, of course with some examples

**Comment by bokey007** [comment]
@robintibor 
Hi, I am new to EEG Decoding
Seems like many of the deep learning model suffer from low validation accuracy (high training accuracy) indication over-fitting.
Not confident but I thing Generation more data may help.

Thus data augmentation methods  will help us all. 

Also is it possible to have GAN like model for eeg-data augmentation ?

**Comment by bruAristimunha** [comment]
Hi @robintibor and @bokey007,

Unfortunately, I don't think the team can implement GAN at the moment due to the schedule and prioritization. Are you interested in implementing @bokey007?

I think the purpose of this issue has already been resolved. MixUp is already implemented, and several augmentations have been implemented. Can we close this issue and maybe continue with a contributing PR (GANs)?

**Comment by robintibor** [comment]
yap, good decision to close
