### ISSUE TITLE
How to get data correctly after setting the data augmentation at the Dataset level?

### ISSUE THREAD

**Issue by h1deOnBush** [braindecode/braindecode#426]
Hi
I want to save the transformed data using augmentation. So I tried like this:
```
splitted = windows_dataset.split('session')
train_set = splitted['session_T']
channel_dropout = ChannelsDropout(probability=.5, p_drop=1)
time_smooth_mask = SmoothTimeMask(probability=.5, mask_len_samples=400)
transforms = [channel_dropout]
composed_transforms = Compose(transforms=transforms)
train_set.transform = composed_transforms
valid_set = splitted['session_E']
X = []
Y = []
x = []
y = []
for trial in train_set:
    X.append(trial[0])
    Y.append(trial[1])
```
but it just don't work. And the error is 
```  
File "/home/zh/workspace/eeg/venv/lib/python3.6/site-packages/braindecode/datasets/base.py", line 199, in __getitem__
    X = self.transform(X)
File "/home/zh/workspace/eeg/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
  return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'y'
```
So Can you tell me how to get data correctly after setting the data augmentation at the Dataset level?

**Comment by martinwimpff** [comment]
Hi @h1deOnBush,
I think I found the problem. Compose needs X and y as input ([see this line](https://github.com/braindecode/braindecode/blob/95bdab990bf4df1e166399ba632682bb1f505371/braindecode/augmentation/base.py#L140)). To verify please check if using one transformation (without Compose) works. If that works please let us know so that we can fix this bug.

**Comment by bruAristimunha** [comment]
Hi @h1deOnBush, 

With the solution proposed by @martinwimpff, were you able to solve the problem?
