### ISSUE TITLE
Improve the installation page

### ISSUE THREAD

**Issue by bruAristimunha** [braindecode/braindecode#464]

**Comment by bruAristimunha** [comment]
Create a poetry lock file

**Comment by ZamboniMarco99** [comment]
Suggestions:
- Since setup.py is considered legacy use [pyproject.toml](https://packaging.python.org/en/latest/tutorials/packaging-projects/)
- Use a frontend tool for packaging, i.e. pdm, poetry
- Fix versions (or ranges of versions) in setup.py or pyproject.toml and test them: is not easy to recognize errors coming from incompatible versions of the dependencies and is not documented what are the ones that work
