### ISSUE TITLE
Tests for dataset classes / functions

### ISSUE THREAD

**Issue by robintibor** [braindecode/braindecode#51]
Need unit tests and possibly acceptance tests for the dataset classes and functions.

**Comment by sliwy** [comment]
A part of tests for `WindowsDataset` and `FixedLengthWindower` in PR https://github.com/robintibor/braindecode-1/pull/2

**Comment by sliwy** [comment]
One more thing, I wonder if we need `tmin` parameter in `FixedLengthWindower` class. In current behavior it is used only for creating `mne.Epochs` objects so it results in removing first epoch from signal because events are uniformly distributed across `raw` signal. It does not make sense for me to add ` tmin`, it should be added only on the level of creating `trials` which can have different classes, not inside a `trial`. Am I correct or I understood sth wrong? @hubertjb @gemeinl

**Comment by gemeinl** [comment]
I think you are right about <code>tmin</code> in <code>FixedLengthWindower</code>. If you can think of a setting where we need this functionality, let us know @hubertjb. 
Also, I think we should rename <code>tmin</code>. We took this name from mne which handles everything in seconds. In braindecode, however, everything is handled in sampels.

**Comment by robintibor** [comment]
outdated
