### ISSUE TITLE
What is `mapping` in `create_windows_from_events`?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [braindecode/braindecode#603]
[Context](https://braindecode.org/stable/auto_examples/applied_examples/plot_sleep_staging_chambon2018.html#extract-windows). How's the "merging" done?

**Comment by bruAristimunha** [comment]
Did that answer your question? @OverLordGoldDragon

**Comment by OverLordGoldDragon** [comment]
My question is, how's it affect "samples", i.e. what's fed along the batch dimension to a model? Put another way, whose z-score is computed [here](https://braindecode.org/stable/auto_examples/applied_examples/plot_sleep_staging_chambon2018.html#window-preprocessing)?

You mentioned concatenation, so is it `x = cat([a, b])`, hence `x.std()`? And would each mapped "category" (`0`, `1`, etc, the values in `mapping`) be fed as a separate input, or are they concatenated along channels? If channels, how are length disparities handled with concatenation?

I've not found much from briefly tracing the source code.

**Comment by bruAristimunha** [comment]
> My question is, how's it affect "samples", i.e. what's fed along the batch dimension to a model? Put another way, whose z-score is computed [here](https://braindecode.org/stable/auto_examples/applied_examples/plot_sleep_staging_chambon2018.html#window-preprocessing)?
> 
> 
> I've not found much from briefly tracing the source code.

Mapping is a transformation applied only to the label (set y), and mne events are label information only. It is not applied to the sample (set x). Only the label is changed; no transformation is made to the data with the mapping option.

About batch, data transformations are always done in the pre-processing set. There's no batch here either; you're applying a transformation to the dataset as a whole. The construction of the data loader happens with Skorch, and that's why we have batch size as a parameter in the EEG classifier; the example with a torch has a good analogy of Skorch and pure pytorch. 

The transformation is applied to all channels by default, except if you set the channels-wise flag, then we have the application for each channel. But I'm not at all confident that I understand this part, to be honest.


> You mentioned concatenation, so is it `x = cat([a, b])`, hence `x.std()`? And would each mapped "category" (`0`, `1`, etc, the values in `mapping`) be fed as a separate input, or are they concatenated along channels? If channels, how are length disparities handled with concatenation?

**Comment by OverLordGoldDragon** [comment]
If I understand correctly - let `3` = `Sleep stage 3` and `4` = `Sleep stage 4` under `Before`:

```
Before -> After
(x0, 3) -> (x0, 3)
(x1, 4) -> (x1, 3)
```

Is this what's happening? If so, makes sense. But then, what does "concatenate" mean here?

 > concatenate the mne events inside the raw dataset.

**Comment by bruAristimunha** [comment]
> If I understand correctly - let `3` = `Sleep stage 3` and `4` = `Sleep stage 4` under `Before`, where pairs are `(data, label)`:
> 
> ```
> Before -> After
> (x0, 3) -> (x0, 3)
> (x1, 4) -> (x1, 3)
> ```
> 
> Is this what's happening? If so, makes sense. But then, what does "concatenate" mean here?

Yes. Sorry, I think now that concatenate was a bad term; rename is better.

> > concatenate the mne events inside the raw dataset.
