### ISSUE TITLE
Loading/organising data tutorial is broken on dev

### ISSUE THREAD

**Issue by itsaphel** [braindecode/braindecode#650]
On the latest master, the example https://braindecode.org/dev/auto_examples/datasets_io/benchmark_lazy_eager_loading.html doesn't seem to work.

e.g.:

```
    for ds in windows_ds.datasets:
        ds.windows.drop_bad()
        assert ds.windows.preload == preload
```

Raises error:
```
    ds.windows.drop_bad()
    ^^^^^^^^^^
AttributeError: 'EEGWindowsDataset' object has no attribute 'windows'
```

Commenting those lines out, the next error appears at:
```
    n_channels = len(dataset.datasets[0].windows.ch_names)
    n_times = len(dataset.datasets[0].windows.times)
```

```
    n_channels = len(dataset.datasets[0].windows.ch_names)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EEGWindowsDataset' object has no attribute 'windows'
```

I presume for the latter, `windows` needs to be renamed to `raw`. Not sure about the former.

**Comment by itsaphel** [comment]
I think the docstring here is also outdated: https://github.com/braindecode/braindecode/blob/master/braindecode/datasets/base.py#L165-L193

**Comment by bruAristimunha** [comment]
Thank youuu very much for catching this error. Just to explain why we didn't catch it before:

Within our tutorials, (almost) all of them are run on almost every PR to ensure that we don't break them. The main problem is that for this one tutorial, we didn't run it because we don't have a CI that can store the dataset without high costs.

In the last code sprint last year, we started to discard this way of accessing the dataset and moved to a new, more pytorch-friendly way.

If I remember correctly, we decided to no longer allow the lazy approach to have drop_bad, because it requires the construction of an mne-epoch object. The big bottleneck in our case.

please feel free invite to report more things, and contribute too ;)
